# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'EuskoEvents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EuskoEvents

  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'Eureka'

end
